# Generated by Django 3.0.7 on 2020-12-06 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('pizzeria', '0001_initial'), ('pizzeria', '0002_auto_20201018_2253'), ('pizzeria', '0003_auto_20201021_2212'), ('pizzeria', '0004_auto_20201022_2107'), ('pizzeria', '0005_auto_20201022_2113'), ('pizzeria', '0006_auto_20201022_2145'), ('pizzeria', '0007_auto_20201023_0003'), ('pizzeria', '0008_auto_20201023_2118'), ('pizzeria', '0009_auto_20201023_2119'), ('pizzeria', '0010_auto_20201023_2127'), ('pizzeria', '0011_auto_20201023_2143'), ('pizzeria', '0012_auto_20201023_2224'), ('pizzeria', '0013_auto_20201024_1956'), ('pizzeria', '0014_order'), ('pizzeria', '0015_auto_20201029_0058'), ('pizzeria', '0016_auto_20201029_0100'), ('pizzeria', '0017_auto_20201029_0105'), ('pizzeria', '0018_auto_20201102_2229'), ('pizzeria', '0019_auto_20201103_2231'), ('pizzeria', '0020_order_order_time'), ('pizzeria', '0021_auto_20201103_2244'), ('pizzeria', '0022_auto_20201103_2246'), ('pizzeria', '0023_auto_20201103_2250'), ('pizzeria', '0024_remove_order_order_time'), ('pizzeria', '0025_auto_20201103_2305'), ('pizzeria', '0026_auto_20201103_2306'), ('pizzeria', '0027_order_order_date'), ('pizzeria', '0028_auto_20201103_2311'), ('pizzeria', '0029_auto_20201103_2348'), ('pizzeria', '0030_auto_20201103_2352'), ('pizzeria', '0031_ingredient_image'), ('pizzeria', '0032_auto_20201107_2348'), ('pizzeria', '0033_auto_20201107_2351'), ('pizzeria', '0034_remove_ingredient_pizza'), ('pizzeria', '0035_auto_20201107_2355'), ('pizzeria', '0036_auto_20201107_2356'), ('pizzeria', '0037_auto_20201116_2213'), ('pizzeria', '0038_auto_20201116_2229'), ('pizzeria', '0039_auto_20201120_1317'), ('pizzeria', '0040_auto_20201123_0018'), ('pizzeria', '0041_auto_20201123_0019'), ('pizzeria', '0042_auto_20201123_0022'), ('pizzeria', '0043_auto_20201123_2109'), ('pizzeria', '0044_auto_20201124_0004'), ('pizzeria', '0045_auto_20201124_0008'), ('pizzeria', '0046_auto_20201124_0012'), ('pizzeria', '0047_auto_20201125_0023'), ('pizzeria', '0048_auto_20201205_2325'), ('pizzeria', '0049_auto_20201205_2352'), ('pizzeria', '0050_auto_20201205_2358')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('in_stock', models.BooleanField(default=True, verbose_name='In stock')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.Category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(default=1, verbose_name='Qty')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Final price')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.Customer', verbose_name='Owner')),
                ('product', models.ManyToManyField(to='pizzeria.Pizza', verbose_name='Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveSmallIntegerField(default=0, verbose_name='Quantity of products')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Final price')),
                ('in_order', models.BooleanField(default=False)),
                ('for_anon_user', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzeria.Customer', verbose_name='Owner')),
                ('products', models.ManyToManyField(blank=True, related_name='related_cart', to='pizzeria.CartProduct')),
            ],
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='pizzeria.Cart', verbose_name='Cart'),
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='pizzeria.CartProduct', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzeria.Pizza', verbose_name='Pizza'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Final price'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('status', models.CharField(choices=[('new', 'New order'), ('in progress', "Order's in progress"), ('ready', "Order's ready"), ('completed', "Order's completed")], default='new', max_length=100, verbose_name="Order's status")),
                ('delivery', models.CharField(choices=[('delivery', 'I need delivery'), ('pickup', "I don't need delivery (pickup)")], default='pickup', max_length=100, verbose_name='Delivery')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment to the order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Order's created at")),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='pizzeria.Customer', verbose_name='Buyer')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_order', to='pizzeria.Cart', verbose_name='Cart')),
                ('order_date_time', models.DateTimeField(verbose_name="Order's delivery date and time")),
            ],
            options={
                'ordering': ('id',),
                'get_latest_by': '-id',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_customer', to='pizzeria.Order', verbose_name='Orders'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(related_name='related_pizza', to='pizzeria.Ingredient', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default=1, max_length=150, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
