# Generated by Django 3.0.7 on 2020-12-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_squashed_0050_auto_20201205_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
