# Generated by Django 3.0.7 on 2020-12-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_auto_20201206_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='related_customer', to='pizzeria.Order', verbose_name='Orders'),
        ),
    ]
