# Generated by Django 3.0.7 on 2021-05-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0004_auto_20201225_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Final price'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_products',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantity of products'),
        ),
    ]
